FROM centos:centos7.9.2009

COPY CentOS-Base.repo CentOS-SCLo-scl.repo CentOS-SCLo-scl-rh.repo epel.repo /etc/yum.repos.d/
COPY docker-entrypoint.sh pyovpn-2.0-py3.8.egg /

RUN yum install -y wget zip unzip curl net-tools

#rpm包保存在当前仓库中,这里使用了加速站点进行下载，如果下载失败，请自行下载
RUN wget -O /openvpn-as-clients.rpm https://ghproxy.cfd/https:/github.com/tcpip4/openvpn-as/releases/download/openvpn-as-clients-33-1/openvpn-as-bundled-clients-33-1.noarch.rpm && wget -O /openvpn-as-2.13.1.rpm https://ghproxy.cfd/https://github.com/tcpip4/openvpn-as/blob/main/centOS-7/openvpn-as-2.13.1_d8cdeb9c-CentOS7.x86_64.rpm && yum localinstall -y /openvpn-as-*  &&  yum clean all && rm -rf /var/cache/yum && rm -rf /openvpn-as-*

RUN mkdir -p /openvpn /ovpn/tmp  /ovpn/sock && sed -i 's#~/tmp#/ovpn/tmp#g;s#~/sock#/ovpn/sock#g' /usr/local/openvpn_as/etc/as_templ.conf

EXPOSE 943/tcp 1194/udp 443/tcp
VOLUME /openvpn

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/usr/local/openvpn_as/scripts/openvpnas", "--nodaemon", "--pidfile=/ovpn/tmp/openvpn.pid"]
